from integrations.connectors.acp import connector as _acp  # noqa: F401
from integrations.connectors.http import connector as _http  # noqa: F401
from integrations.connectors.internal import connector as _internal  # noqa: F401
from integrations.connectors.temp import connector as _temp  # noqa: F401
from integrations.connectors.openclaw import connector as _openclaw  # noqa: F401
from integrations.connectors.pi import connector as _pi  # noqa: F401
from integrations.connectors.codex import connector as _codex  # noqa: F401
from integrations.connectors.claude import connector as _claude  # noqa: F401
from integrations.connectors.gemini import connector as _gemini  # noqa: F401
from integrations.connectors.cursor import connector as _cursor  # noqa: F401
from integrations.connectors.copilot import connector as _copilot  # noqa: F401
from integrations.connectors.droid import connector as _droid  # noqa: F401
from integrations.connectors.iflow import connector as _iflow  # noqa: F401
from integrations.connectors.kilocode import connector as _kilocode  # noqa: F401
from integrations.connectors.kimi import connector as _kimi  # noqa: F401
from integrations.connectors.kiro import connector as _kiro  # noqa: F401
from integrations.connectors.opencode import connector as _opencode  # noqa: F401
from integrations.connectors.qoder import connector as _qoder  # noqa: F401
from integrations.connectors.qwen import connector as _qwen  # noqa: F401
from integrations.connectors.trae import connector as _trae  # noqa: F401
