# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

"""Typed ACPX meta-harness for ClawCross external agent runtimes."""

from integrations.acpx_harness.capabilities import capability_profile_for_provider, capability_profile_to_dict
from integrations.acpx_harness.auth_status import provider_auth_status
from integrations.acpx_harness.bench import provider_conformance_matrix, provider_conformance_row
from integrations.acpx_harness.dispatcher import AcpxHarnessDispatcher, get_acpx_harness_dispatcher
from integrations.acpx_harness.executor import (
    ExecutorEvent,
    ExecutorEventKind,
    cancelled_executor_event,
    executor_event_to_dict,
    executor_events_to_dicts,
    failed_executor_event,
    stream_update_to_executor_event,
    text_to_executor_events,
    trace_to_executor_events,
)
from integrations.acpx_harness.mcp_tools import (
    MaterializedToolManifest,
    materialize_agent_tool_bindings,
    materialize_tool_scope,
    materialized_tool_manifest_to_dict,
)
from integrations.acpx_harness.mcp_runtime import (
    McpRuntimeError,
    build_session_mcp_tool_call,
    call_mcp_runner_cache_reset,
    call_mcp_runner_jsonrpc,
    call_session_mcp_tool,
    list_session_mcp_tools,
    list_session_mcp_jsonrpc_tools,
    manifest_name_from_mcp_wire_name,
    mcp_wire_tool_name,
    redact_mcp_tool_call_request,
    session_mcp_manifest,
    upsert_session_mcp_tool_manifest,
)
from integrations.acpx_harness.policy_bridge import (
    PolicyBridge,
    PolicyBridgeVerdict,
    build_policy_bridge,
    evaluate_tool_call_policy,
    evaluate_trace_policy,
    policy_bridge_to_dict,
    policy_verdict_to_dict,
)
from integrations.acpx_harness.registry import get_provider_spec, list_provider_specs
from integrations.acpx_harness.schema import (
    CapabilityProfile,
    HarnessAgentSpec,
    HarnessExecutorSpec,
    HarnessPolicySpec,
    HarnessToolSpec,
    PreparedHarnessStream,
    ProviderSpec,
    ProbeResult,
    RunEvent,
    RunOptions,
    RunRequest,
    RunResult,
    SessionRef,
)
from integrations.acpx_harness.specs import (
    AgentSpecValidationError,
    agent_spec_to_dict,
    agent_spec_to_run_request,
    compile_agent_spec,
    load_agent_spec,
    load_agent_spec_mapping,
    validate_agent_spec_mapping,
)
from integrations.acpx_harness.subagents import materialize_declared_agent_sessions
from integrations.acpx_harness.tool_inheritance import (
    ToolInheritanceError,
    resolve_child_tools,
    resolve_declared_subagent_tools,
    tool_scope_to_dict,
)

__all__ = [
    "AcpxHarnessDispatcher",
    "CapabilityProfile",
    "ExecutorEvent",
    "ExecutorEventKind",
    "HarnessAgentSpec",
    "HarnessExecutorSpec",
    "HarnessPolicySpec",
    "HarnessToolSpec",
    "MaterializedToolManifest",
    "McpRuntimeError",
    "PreparedHarnessStream",
    "ProviderSpec",
    "ProbeResult",
    "PolicyBridge",
    "PolicyBridgeVerdict",
    "RunEvent",
    "RunOptions",
    "RunRequest",
    "RunResult",
    "SessionRef",
    "ToolInheritanceError",
    "AgentSpecValidationError",
    "agent_spec_to_dict",
    "agent_spec_to_run_request",
    "build_policy_bridge",
    "capability_profile_for_provider",
    "capability_profile_to_dict",
    "cancelled_executor_event",
    "compile_agent_spec",
    "executor_event_to_dict",
    "executor_events_to_dicts",
    "evaluate_tool_call_policy",
    "evaluate_trace_policy",
    "failed_executor_event",
    "get_acpx_harness_dispatcher",
    "get_provider_spec",
    "load_agent_spec",
    "load_agent_spec_mapping",
    "validate_agent_spec_mapping",
    "list_provider_specs",
    "materialize_agent_tool_bindings",
    "materialize_declared_agent_sessions",
    "materialize_tool_scope",
    "materialized_tool_manifest_to_dict",
    "build_session_mcp_tool_call",
    "call_mcp_runner_cache_reset",
    "call_mcp_runner_jsonrpc",
    "call_session_mcp_tool",
    "list_session_mcp_tools",
    "list_session_mcp_jsonrpc_tools",
    "manifest_name_from_mcp_wire_name",
    "mcp_wire_tool_name",
    "redact_mcp_tool_call_request",
    "policy_bridge_to_dict",
    "policy_verdict_to_dict",
    "provider_conformance_matrix",
    "provider_conformance_row",
    "provider_auth_status",
    "resolve_child_tools",
    "resolve_declared_subagent_tools",
    "session_mcp_manifest",
    "stream_update_to_executor_event",
    "text_to_executor_events",
    "tool_scope_to_dict",
    "trace_to_executor_events",
    "upsert_session_mcp_tool_manifest",
]
